### ISSUE TITLE
HHL for calibration

### ISSUE THREAD

**Issue by NicoRenaud** [NLESC-quantum/quantum_comp#31]
There is a generic HHL algo implemented in Qiskit. We could use it to see if it could be useful for calibration

**Comment by NicoRenaud** [comment]
https://github.com/Qiskit/qiskit-terra/blob/main/qiskit/algorithms/linear_solvers/hhl.py

**Comment by PabRod** [comment]
Some preliminary conclusions:

The more I work on HHL, the more convinced I am that it is not what we need. The `qiskit` implementation of HHL only allows extracting either <x|x>, the arithmetic average of |x>'s coefficients or <x|B|x>. The last one looks promising, but unfortunately B is not a generic matrix: it has to be a Toeplitz tridiagonal matrix. Other subcases than those seem to be deliberately not implemented, probably because they don't offer any computational advantage compared to other methods.

Furthermore, the whole method is known for not returning a complete solution.

**Comment by PabRod** [comment]
Task for me: document my conclusions on the [HHL readme](https://github.com/NLESC-quantum/quantum_comp/blob/main/redcal/hhl/README.md).

**Comment by PabRod** [comment]
Managed to run it successfully on the IBMq servers.
