### ISSUE TITLE
VQLS Algorithm for linear solver

### ISSUE THREAD

**Issue by NicoRenaud** [NLESC-quantum/quantum_comp#5]
What are the advantages/drawback compared to HHL ?
Any use in the calibration pipeline ?

## References
- https://qiskit.org/textbook/ch-paper-implementations/vqls.html
- Variational Quantum Linear Solver. [Arxiv](https://arxiv.org/abs/1909.05820)
- Decent explanation of the Variational Principle in [Qiskit](https://qiskit.org/textbook/ch-applications/vqe-molecules.html).
   - An even better (and shorter) one is available on Sakurai's Modern Quantum Mechanics, episode 5.4.

**Comment by PabRod** [comment]
The purpose is to solve the linear system for x, for a given A and b:

<img src="https://render.githubusercontent.com/render/math?math=A \left|{x}\right\rangle = \left|{b}\right\rangle">

The key idea is to find the ground energy for the projection hamiltonian:

<img src="https://render.githubusercontent.com/render/math?math=H = 1 - \left|{b}\right\rangle \left\langle{b}\right| ">

Instead of trying to solve directly, we'd rather apply the variational principle to the functional:

<img src="https://render.githubusercontent.com/render/math?math=\epsilon[\phi] \equiv \frac{\left\langle{\phi}\right|H\left|{\phi}\right\rangle}{\left\langle{\phi}\right|\left|{\phi}\right\rangle}">

Where:

<img src="https://render.githubusercontent.com/render/math?math=\left|{\phi}\right\rangle \equiv A \left|{\psi(k)}\right\rangle">

<img src="https://render.githubusercontent.com/render/math?math=\left|{\psi(k)}\right\rangle \equiv V(k) \left|{0}\right\rangle">

and

<img src="https://render.githubusercontent.com/render/math?math=\left|{b}\right\rangle \equiv U \left|{0}\right\rangle">

Additionally, it seems to be important to express A as a linear combination of unitary matrices. Nothing is mentioned about the unicity nor existence of this decomposition.

**Comment by NicoRenaud** [comment]
Msc thesis that applies VQLS to FEM and spend some time on matrix decomposition : file:///C:/Users/NicolasRenaud/Downloads/MsC_Thesis_E_Cappanera_4943872_Final.pdf

**Comment by PabRod** [comment]
## Decomposition in unitary matrices

According to [this](https://math.stackexchange.com/a/1710390), the decomposition in unitaries can always be done using 4 matrices or less. They also explain the algorithm.

**Comment by NicoRenaud** [comment]
It's done and it's part of qalcore. We might want to upstream it to qiskit
